# Generated by Django 6.1 on 2026-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_terima', models.DateField(auto_now_add=True)),
                ('kategori', models.CharField(choices=[('Surat Resmi', 'Surat Resmi'), ('Paket Pribadi', 'Paket Pribadi'), ('Inventaris IT', 'Inventaris IT')], max_length=50)),
                ('pengirim', models.CharField(max_length=255)),
                ('nama_penerima', models.CharField(max_length=255)),
                ('nik_penerima', models.CharField(max_length=50)),
                ('foto_barang', models.ImageField(blank=True, null=True, upload_to='foto_barang/')),
                ('status', models.CharField(choices=[('Di Resepsionis', 'Di Resepsionis'), ('Sudah Diambil', 'Sudah Diambil')], default='Di Resepsionis', max_length=50)),
                ('dob_pengambil', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
