# Generated by Django 6.1 on 2026-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumenmasuk',
            options={'verbose_name_plural': 'Dokumen Masuk'},
        ),
        migrations.AlterField(
            model_name='dokumenmasuk',
            name='nik_penerima',
            field=models.CharField(max_length=50, verbose_name='NIK penerima'),
        ),
    ]
