# Generated by Django 6.1 on 2026-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_alter_dokumenmasuk_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_resi_internal', models.CharField(blank=True, max_length=20, unique=True)),
                ('tanggal_terima', models.DateField(auto_now_add=True)),
                ('nama_pengirim', models.CharField(max_length=255)),
                ('nik_pengirim', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('foto_dokumen', models.ImageField(blank=True, null=True, upload_to='foto_dokumen/')),
                ('resi_jne', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Menunggu Kurir', 'Menunggu Kurir'), ('Sedang Dikirim JNE', 'Sedang Dikirim JNE'), ('Selesai', 'Selesai')], default='Menunggu Kurir', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dokumen Keluar',
            },
        ),
    ]
