# Generated by Django 6.1 on 2026-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0003_dokumenkeluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkeluar',
            name='nik_pengirim',
            field=models.CharField(max_length=50, verbose_name='NIK pengirim'),
        ),
    ]
