# Generated by Django 6.1 on 2026-09-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0004_alter_dokumenkeluar_nik_pengirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenmasuk',
            name='tanggal_diambil',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pengambilan Barang'),
        ),
        migrations.AlterField(
            model_name='dokumenmasuk',
            name='dob_pengambil',
            field=models.DateField(blank=True, help_text='Sebutkan tanggal lahir saat pengambilan barang untuk verifikasi identitas.', null=True, verbose_name='Tanggal Lahir Pengambil (Verifikasi)'),
        ),
    ]
