# Generated by Django 6.1 on 2026-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0005_dokumenmasuk_tanggal_diambil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkeluar',
            name='resi_jne',
            field=models.URLField(null=True),
        ),
    ]
