# Generated by Django 6.1 on 2026-09-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0006_alter_dokumenkeluar_resi_jne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkeluar',
            name='resi_jne',
            field=models.URLField(blank=True, null=True, verbose_name='URL Resi JNE'),
        ),
    ]
