# Generated by Django 6.1 on 2026-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0007_alter_dokumenkeluar_resi_jne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50, unique=True, verbose_name='NIK')),
                ('nama_lengkap', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Data Karyawan',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
