# Generated by Django 6.1 on 2026-09-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0008_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pt', models.CharField(max_length=255, unique=True, verbose_name='Nama PT / Instansi')),
            ],
            options={
                'verbose_name': 'PT / Instansi',
                'verbose_name_plural': 'Data PT / Instansi',
                'ordering': ['nama_pt'],
            },
        ),
        migrations.AlterField(
            model_name='dokumenkeluar',
            name='status',
            field=models.CharField(choices=[('Menunggu Kurir', 'Menunggu Kurir'), ('Sudah Diserahkan ke JNE', 'Sudah Diserahkan ke JNE')], default='Menunggu Kurir', max_length=50),
        ),
    ]
