# Generated by Django 6.1 on 2026-09-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0009_datapt_alter_dokumenkeluar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenmasuk',
            name='jenis_pengirim',
            field=models.CharField(choices=[('PT', 'PT / Instansi'), ('Non-PT', 'Non-PT / Perseorangan')], default='PT', max_length=20, verbose_name='Jenis Pengirim'),
        ),
        migrations.AddField(
            model_name='dokumenmasuk',
            name='pt_pengirim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dokumen.datapt', verbose_name='PT / Instansi Pengirim'),
        ),
        migrations.AlterField(
            model_name='dokumenmasuk',
            name='pengirim',
            field=models.CharField(max_length=255, verbose_name='Nama Pengirim'),
        ),
    ]
