# Generated by Django 6.1 on 2026-09-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0010_dokumenmasuk_jenis_pengirim_dokumenmasuk_pt_pengirim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenmasuk',
            name='kategori',
            field=models.CharField(choices=[('Surat Resmi', 'Surat Resmi'), ('Paket Pribadi', 'Paket Pribadi')], max_length=50),
        ),
    ]
