# Generated by Django 6.1 on 2026-09-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0011_alter_dokumenmasuk_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_supplier', models.CharField(max_length=100, unique=True, verbose_name='Kode Supplier')),
                ('nama_supplier', models.CharField(max_length=255, verbose_name='Nama Supplier')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Data Supplier',
                'ordering': ['nama_supplier'],
            },
        ),
        migrations.AlterField(
            model_name='dokumenmasuk',
            name='pt_pengirim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dokumen.supplier', verbose_name='PT / Instansi Pengirim'),
        ),
        migrations.DeleteModel(
            name='DataPT',
        ),
    ]
