# Generated by Django 6.1 on 2026-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0012_supplier_alter_dokumenmasuk_pt_pengirim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumenkeluar',
            name='nik_pengirim',
        ),
        migrations.RemoveField(
            model_name='dokumenmasuk',
            name='nik_penerima',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='nik',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jabatan'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='kode_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Kode Karyawan'),
        ),
        migrations.AlterField(
            model_name='dokumenmasuk',
            name='nama_penerima',
            field=models.CharField(max_length=255, verbose_name='Nama Penerima'),
        ),
    ]
