# Generated by Django 6.1 on 2026-09-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0013_remove_dokumenkeluar_nik_pengirim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(max_length=255, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='kode_karyawan',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kode Karyawan'),
        ),
    ]
