# Generated by Django 6.1 on 2026-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0015_karyawan_aktif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkeluar',
            name='status',
            field=models.CharField(choices=[('Menunggu Kurir', 'Menunggu Kurir'), ('Sudah Diserahkan ke JNE', 'Sudah Diserahkan ke JNE'), ('Paket Kembali', 'Paket Kembali')], default='Menunggu Kurir', max_length=50),
        ),
    ]
