# Generated by Django 6.1 on 2026-09-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0017_riwayat_status_dokumen'),
        ('dokumen', '0017_riwayatstatusdokumenmasuk_status_sebelumnya_and_more'),
    ]

    operations = [
    ]
