# Generated by Django 6.1 on 2026-09-18 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0018_merge_20260916_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenmasuk',
            name='karyawan_penerima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumen_masuk', to='dokumen.karyawan', verbose_name='Karyawan Penerima'),
        ),
    ]
