# Generated by Django 6.1 on 2026-09-18 03:36

from django.db import migrations


def fill_karyawan_penerima(apps, schema_editor):
    DokumenMasuk = apps.get_model('dokumen', 'DokumenMasuk')
    Karyawan = apps.get_model('dokumen', 'Karyawan')

    ambiguous_count = 0
    not_found_count = 0
    updated_count = 0

    for doc in DokumenMasuk.objects.filter(karyawan_penerima__isnull=True):
        nama = doc.nama_penerima.strip() if doc.nama_penerima else ""
        if not nama:
            continue
            
        karyawan_matches = Karyawan.objects.filter(nama_lengkap__iexact=nama)
        
        if karyawan_matches.count() == 1:
            doc.karyawan_penerima = karyawan_matches.first()
            doc.save(update_fields=['karyawan_penerima'])
            updated_count += 1
        elif karyawan_matches.count() > 1:
            ambiguous_count += 1
        else:
            not_found_count += 1

    print(f"\nData Migration Report:")
    print(f"Updated: {updated_count}")
    print(f"Ambiguous (Skipped): {ambiguous_count}")
    print(f"Not Found (Skipped): {not_found_count}")


def reverse_fill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0019_dokumenmasuk_karyawan_penerima'),
    ]

    operations = [
        migrations.RunPython(fill_karyawan_penerima, reverse_fill)
    ]
