# Generated by Django 6.1 on 2026-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0020_fill_karyawan_penerima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenmasuk',
            name='nama_penerima',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Penerima'),
        ),
    ]
